import pandas as pd

from google.cloud import storage


data = pd.read_csv('https://controllerdata.lacity.org/api/views/g9h8-fvhu/rows.csv', low_memory=False)
df = data[data['DEPARTMENT_TITLE'] == 'CITY ATTORNEY']
cols = ["RECORD_NBR", "JOB_CLASS_PGRADE", "PAY_YEAR", "GENDER", "ETHNICITY", "JOB_TITLE", "JOB_STATUS", "EMPLOYMENT_TYPE"]

df2 = df.groupby(cols)["REGULAR_PAY"].sum().reset_index()
df2['JOB_CLASS_PGRADE_NUMERIC'] = df2['JOB_CLASS_PGRADE'].rank(method='dense', ascending=True).astype(int)
df2['JOB_CLASS_PGRADE_RANK'] = df2.groupby('RECORD_NBR')['JOB_CLASS_PGRADE_NUMERIC'].rank('dense').astype(int)
df2['NEW_HIRE'] = df2.groupby('RECORD_NBR')['PAY_YEAR'].rank('dense').astype(int)

ETHNICITY_MAPPING = {
  'CAUCASIAN': 'CAUCASIAN',
  'HISPANIC': 'HISPANIC',
  'ASIAN': 'ASIAN',
  'BLACK': 'BLACK',
  'FILIPINO': 'ASIAN',
  'OTHER': 'OTHER',
  'TWO OR MORE RACES': 'OTHER',
  'AMERICAN INDIAN': 'OTHER'
}


df2['ETHNICITY'] = df2['ETHNICITY'].str.strip().replace(ETHNICITY_MAPPING)


JOB_TITLE_MAPPING_01 = {
  'ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'CHIEF ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'CITY ATTORNEY ACCOUNTING CLERK': 'ACCOUNTING CLERK',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR I': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR II': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR III': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR IV': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY CHIEF ADMINISTRATIVE ASSISTANT': 'CHIEF ADMINISTRATIVE ASSISTANT',
  'CITY ATTORNEY CHIEF INVESTIGATOR': 'CHIEF INVESTIGATOR',
  'CITY ATTORNEY FINANCIAL MANAGER': 'FINANCIAL MANAGER',
  'CITY ATTORNEY INVESTIGATOR I': 'INVESTIGATOR',
  'CITY ATTORNEY INVESTIGATOR II': 'INVESTIGATOR',
  'CITY ATTORNEY INVESTIGATOR III': 'INVESTIGATOR',
  'DEPUTY CITY ATTORNEY I': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY II': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY III': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY IV': 'DEPUTY CITY ATTORNEY ',
  'EXECUTIVE LEGAL SECRETARY I': 'EXECUTIVE LEGAL SECRETARY',
  'HEARING OFFICER CITY ATTORNEY': 'HEARING OFFICER',
  'LEGAL ASSISTANT': 'LEGAL ASSISTANT',
  'LEGAL ASSISTANT I': 'LEGAL ASSISTANT',
  'LEGAL ASSISTANT II': 'LEGAL ASSISTANT',
  'LEGAL CLERK II': 'LEGAL CLERK',
  'LEGAL SECRETARY I': 'LEGAL SECRETARY',
  'LEGAL SECRETARY II': 'LEGAL SECRETARY',
  'LEGAL SECRETARY III': 'LEGAL SECRETARY',
  'PARALEGAL I': 'PARALEGAL',
  'PARALEGAL II': 'PARALEGAL',
  'PARALEGAL III': 'PARALEGAL',
  'PRINCIPAL CLERK CITY ATTORNEY I': 'PRINCIPAL CLERK CITY ATTORNEY',
  'PRINCIPAL CLERK CITY ATTORNEY II': 'PRINCIPAL CLERK CITY ATTORNEY',
  'SENIOR ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'SENIOR LEGAL ASSISTANT': 'LEGAL ASSISTANT',
  'SENIOR LEGAL CLERK I': 'LEGAL CLERK',
  'SENIOR LEGAL CLERK II': 'LEGAL CLERK',
  'SENIOR WITNESS SERVICE COORDINATOR': 'WITNESS SERVICE COORDINATOR',
  'WITNESS SERVICE COORDINATOR': 'WITNESS SERVICE COORDINATOR',
  'LEGAL CLERK I': 'LEGAL CLERK'
}


JOB_TITLE_MAPPING_02 = {
  'ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'CHIEF ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'CITY ATTORNEY ACCOUNTING CLERK': 'ACCOUNTING CLERK',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR I': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR II': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR III': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY ADMINISTRATIVE COORDINATOR IV': 'ADMINISTRATIVE COORDINATOR',
  'CITY ATTORNEY CHIEF ADMINISTRATIVE ASSISTANT': 'CHIEF ADMINISTRATIVE ASSISTANT',
  'CITY ATTORNEY CHIEF INVESTIGATOR': 'CHIEF INVESTIGATOR',
  'CITY ATTORNEY FINANCIAL MANAGER': 'FINANCIAL MANAGER',
  'CITY ATTORNEY INVESTIGATOR I': 'INVESTIGATOR',
  'CITY ATTORNEY INVESTIGATOR II': 'INVESTIGATOR',
  'CITY ATTORNEY INVESTIGATOR III': 'INVESTIGATOR',
  'DEPUTY CITY ATTORNEY I': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY II': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY III': 'DEPUTY CITY ATTORNEY ',
  'DEPUTY CITY ATTORNEY IV': 'DEPUTY CITY ATTORNEY ',
  'EXECUTIVE LEGAL SECRETARY I': 'EXECUTIVE LEGAL SECRETARY',
  'HEARING OFFICER CITY ATTORNEY': 'HEARING OFFICER',
  'LEGAL ASSISTANT': 'LEGAL ASSISTANT',
  'LEGAL ASSISTANT I': 'LEGAL ASSISTANT',
  'LEGAL ASSISTANT II': 'LEGAL ASSISTANT',
  'LEGAL CLERK II': 'LEGAL CLERK',
  'LEGAL SECRETARY I': 'LEGAL SECRETARY',
  'LEGAL SECRETARY II': 'LEGAL SECRETARY',
  'LEGAL SECRETARY III': 'LEGAL SECRETARY',
  'PARALEGAL I': 'PARALEGAL',
  'PARALEGAL II': 'PARALEGAL',
  'PARALEGAL III': 'PARALEGAL',
  'PRINCIPAL CLERK CITY ATTORNEY I': 'PRINCIPAL CLERK CITY ATTORNEY',
  'PRINCIPAL CLERK CITY ATTORNEY II': 'PRINCIPAL CLERK CITY ATTORNEY',
  'SENIOR ASSISTANT CITY ATTORNEY': 'ASSISTANT CITY ATTORNEY',
  'SENIOR LEGAL ASSISTANT': 'LEGAL ASSISTANT',
  'SENIOR LEGAL CLERK I': 'LEGAL CLERK',
  'SENIOR LEGAL CLERK II': 'LEGAL CLERK',
  'SENIOR WITNESS SERVICE COORDINATOR': 'WITNESS SERVICE COORDINATOR',
  'WITNESS SERVICE COORDINATOR': 'WITNESS SERVICE COORDINATOR',
  'LEGAL CLERK I': 'LEGAL CLERK'
}

df2['GROUPING_01'] = df2['JOB_TITLE'].str.strip().replace(JOB_TITLE_MAPPING_01)
df2['GROUPING_01'] = df2['GROUPING_01'].str.strip()

df2['GROUPING_02'] = df2['JOB_TITLE'].str.strip().replace(JOB_TITLE_MAPPING_02)
df2['GROUPING_02'] = df2['GROUPING_02'].str.strip()


# drop 1st year
new_hires = df2[(df2['PAY_YEAR'] != 2013) & (df2['NEW_HIRE'] == 1)]

# drop duplicates
new_hires = new_hires.drop_duplicates(subset='RECORD_NBR', keep='first')


bucket_name = "YOUR_NAME"
fname = "promotions.csv"

client = storage.Client()
bucket = client.get_bucket(bucket_name)
blob = storage.Blob(f"data/{fname}", bucket)
df_str = new_hires.to_csv(index=False, encoding='utf-8')
blob.upload_from_string(df_str)